baseURL: https://joselondono.co/
languageCode: es
defaultContentLanguage: es
title: José Londoño

params:
    defaultTheme: light

    profileMode:
        enabled: true
        title: "Hola! Soy José Londoño 👋🏻"
        subtitle: "Soy un científico de dato basado en Medellín, Colombia. 🇨🇴"
        imageUrl: "assets/me.jpg" 
        imageTitle: "Me" # optional
        imageWidth: 350 # custom size
        imageHeight: 350 # custom size
        buttons:
          - name: Blog
            url: "/blog"
          - name: Github
            url: "https://github.com/jlondonob"

    socialIcons:
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/jose-londono-botero"
        - name: "Github"
          url: "https://github.com/jlondonob"
        - name: "Twitter"
          url: "https://twitter.com/jlondonobo"
        - name: "Instagram"
          url: "https://www.instagram.com/joselipis27/"
        - name: "Email"
          url: "mailto:j.londonobo@gmail.com"

menu:
  main:
  - identifier: About
    name: Sobre Mi
    url: /about
    weight: 10
  - identifier: Blog
    name: Blog
    url: /blog/
    weight: 20
  - identifier: Contacto
    name: Contacto
    url: /contact
    weight: 30

    
    ShowShareButtons: true

    ShowReadingTime: true

    ShowCodeCopyButtons: true


theme: PaperMod


